" config 

	set number
	set relativenumber
	set ruler
	set autowrite

	set list
	set listchars=tab:\|\ ,trail:$,extends:>,precedes:<
	set cursorline
	set cursorcolumn
	set incsearch
	set hlsearch

" Vundle
" ------

	set nocompatible              " be iMproved, required
	filetype off                  " required

	" set the runtime path to include Vundle and initialize
	set rtp+=~/.vim/bundle/Vundle.vim
	call vundle#begin()

		Plugin 'VundleVim/Vundle.vim'
		Plugin 'tpope/vim-fugitive'
		Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
		Plugin 'ycm-core/YouCompleteMe'
		Plugin 'morhetz/gruvbox'

	call vundle#end()            " required
	filetype plugin indent on    " required

" YouCompleteMe

	let g:ycm_clangd_uses_ycmd_caching = 0
	let g:ycm_clangd_binary_path = exepath("clangd")

" gruvbox
" -------
	let g:gruvbox_italic=1
	colorscheme gruvbox
	set background=dark
